yangshun/tech-interview-handbook

.travis.yml
While reading [Front End Job Interview Questions](https://github.com/yangshun/tech-interview-handbook/blob/master/front-end/interview-questions.md) I stumbled upon the dead link http://jgthms.com/css-interview-questions-and-answers.html
This PR adding the awesome bot which will automatically go through all links and report if anything is dead. It will still allow redirects and duplicates.
Here's the current state:
```
> Checking links in algorithms/array.md
> Will allow duplicate links
> Will allow redirects
> Will not save results
Links to check: 6
1. http://blog.gainlo.co/index.php/2016/06/01/subarray-with-given-sum/ 
2. http://blog.gainlo.co/index.php/2016/07/19/3sum/ 
3. http://blog.gainlo.co/index.php/2016/05/10/duplicate-elements-of-an-array/ 
4. …
```
=> Add awesome_bot to automatically check if links are dead

front-end/css.md
- Covered Specificity, Positioning and Floats
- Added links to Mozilla css docs for each list item
=> Added Writeup for CSS in front-end folder resources

algorithms/README.md
As per title, @yangshun maybe choose other similar questions? Or rearrange them such that premium always come behind.
=> Indicate problems that are leetcode premium only

utilities/javascript/binarySearch.js, utilities/python/binary_search.py
Really just a personal preference. Feel free to reject if you want to keep it as is.
=> return -1 if target is not in array

preparing/README.md
Great guide, thanks for assembling all these resources. Just a few edits that clarify some of the language!
=> Grammar fixes for tense, punctuation and wording.

README.md
Add some fluff to increase conversion rates.
=> Add more marketing content to README

non-technical/behavioral.md
I wasn't sure this sentence was in error or not and I wasn't able to find any quote like it. I did find this one however, https://www.glassdoor.com/Interview/What-does-it-mean-to-belong-QTN_1980892.htm, and changed the quote to reflect it.
=> Sentence clarification

front-end/interview-questions.md
```
console.log(baz === undefined); // undefined
```
Should be either `console.log(baz === undefined); // true` or `console.log(baz); // undefined`
Also there was a code highlighting tag omitted
=> Fixed errors in "undefined and undeclared" section

front-end/interview-questions.md
Added a new answer to question:
__What kind of things must you be wary of when designing or developing for multilingual sites?__
=> Added to Front-End Interview questions: more answers to question

front-end/interview-questions.md
Correcting full stop typo to comma.
=> Grammar correction

front-end/interview-questions.md, non-technical/resume.md
=> Add resume tips section

non-technical/questions-to-ask.md
Hi.
I've added a few good questions to ask at interview. I added a new section Product with product related questions. And I added a couple of questions in Technical section. One of them is rather nice to be highlighted, in my opinion.
=> Added new questions to questions-to-ask.md

front-end/interview-questions.md
Just some small typos that I found while reading the tips. Nice guide btw!
=> Fix small typos

preparing/cheatsheet.md
Added a legend for each marker. I got confused for a moment when I saw ⚠️
=> Add legend to cheatsheet

algorithms/README.md
=> Fix Missing Link for Trie

algorithms/dynamic-programming.md
Changes:
- Ran content through a grammar checker.
- Break the code example after column 100 to remove horizontal scrollbar when viewing on GitHub.
- Put content inside 'Problem examples' H2 header.
=> Visual changes

utilities/javascript/binToInt.js, utilities/javascript/binarySearch.js, utilities/javascript/deepEqual.js, utilities/javascript/graphTopoSort.js, utilities/javascript/intToBin.js, utilities/javascript/intervalsIntersect.js, utilities/javascript/intervalsMerge.js, utilities/javascript/matrixClone.js, utilities/javascript/matrixTranspose.js, utilities/javascript/matrixTraverse.js
- `binToInt`
- `intToBin`
- `intervalsIntersect`
- `intervalsMerge`
- `matrixClone`
- `matrixTranspose`
- `matrixTraverse`
=> Add a ton of JS algo snippets

algorithms/queue.md
This PR adds the classic "Implement a Queue with Two Stacks" problem to the algorithms section.
=> Add two-stack-queue problem

utilities/python/quick_select.py
And an additional partition by value function which can't be used in QuickSelect -- but still useful for partitioning when you want to bound your recursion depth by the range of the input values, and not the length of the array.
=> Add QuickSelect algorithm

utilities/python/linked_list.py
And a whole suite of helper functions that modify the list.
=> Add Linked List

interviewers/basics.md
Thought I would start the interviewers doc having been on that side of the table a few times.
=> Starting interviewer docs #55

front-end/interview-questions.md
Added official reference to question: https://github.com/yangshun/tech-interview-handbook/blob/master/front-end/interview-questions.md#what-are-data--attributes-good-for
=> Added official w3c spec reference to question:  data-* attr HTML

algorithms/string.md
=> Fix grammar

front-end/interview-questions.md
Added reference to CSS questions:
* _Explain CSS sprites, and how you would implement them on a page or site._
* _What is the difference between classes and IDs in CSS?_
=> Added Reference to CSS quesitons

front-end/interview-questions.md
I think it is necessary to mention the way to iterating over all non-enumerable properties
=> Improve answer for enumerating through JS object properties

non-technical/behavioral.md
Did some cleanup RE the phrasing and grammar of some of the questions, making them more consistent.
=> Fix grammar/phrasing and typos in behavioral.md

algorithms/string.md
"Count and say" is at line 43 again
=> remove duplicate question

algorithms/array.md
Split problems based on difficulty from Geeks for Geeks: https://www.geeksforgeeks.org/find-the-element-that-appears-once/
Add solutions to each problem.
=> Add solutions to Array problems.

algorithms/array.md
added a problem I had from an interview at a fortune100 company
=> Add longest consecutive elements sequence question

algorithms/README.md
There was no link to Longest Common Subsequence and there was no question on leetcode for it. I placed a geeksforgeeks link to this problem which has solutions and explanation.
=> algorithms: add link to Longest Common Subsequence problem

contents/landscape.md
This PR fixes the wording of the sentence.
=> fixes the wording

contents/picking-a-language.md
This PR fixes the working of the sentence.
=> Fix wording

contents/understanding-compensation.md
=> contents: fix a typo

contents/interview-formats.md
Hello, I was reading the handbook (great job here btw) and notice this typo.
=> misc: fix typo

contents/best-practice-questions.md
The LeetCode practice question "Merge K Sorted Lists" is listed in both week 2 and 4.
=> misc: remove duplicate entry for "Merge K Sorted Lists"

contents/interview-formats.md
Corrected vanilla JS requirement
Added 1 x non-technical interview
Removed outdated no-laptops requirement
=> contents: update Google technical interview format

contents/algorithms/graph.md
The changes I'm planning are as follows:
1. The current method for traversing graphs (represented as 2D grids) shows a 
recursive implementation. I'm following an iterative implementation that uses
`deque` data structure which can function as either a queue (for `BFS`) and 
stack (for `DFS`) to provide more effecient insertion and deletion operations.
2. Using `namedtuple` data structure to use `x` or `y` to access coordinates in 
place of indices.
3. Add a placeholder function `is_valid` to check for those cells that may be 
invalid (this function will vary as per what the question requires)
4. Insert into the `deque` first and check if the nodes are valid later(as 
opposed to checking boundary conditions and visited/valid seperately)
=> contents: modify graph search algorithm

contents/interview-formats.md
I've been reading through this handbook (very helpful and amazing, btw) and noticed a typo in the Phone Interview section. I also changed the tense to make a bit more sense.
=> fixed typo in Phone Interview section

contents/self-introduction.md
Fix is more semantics than spelling correction.
=> Fix Typo (Semantics): Under "Why do they want you" section.

.gitpod.yml, README.md
Hi! there :slightly_smiling_face: 
This PR simplifies code contributions by adding configuration for gitpod (A Free online VS Code like Ide). With a single click, it will launch a ready to code workspace with all the dependencies being pre-installed & the start & build scripts in process so that anyone interested in contributing can start coding straight away without wasting any time on dev setup.
You can give it a try on My Fork of the repo:
https://gitpod.io/#https://github.com/nisarhassan12/tech-interview-handbook
=> misc: simplify code contributions by automating the dev setup with Gitpod

website/blog/2020-05-28-summing-root-to-leaf-numbers.md, website/docusaurus.config.js
This PR is a follow-up to issue #165 . It adds a blog to the tech-interview handbook website and adds my post to it. 
Please do let me know if any changes are required :)
=> add blog and blogpost

contents/behavioral-questions.md
- Added more general questions
- Added more tricky (uncommon) tech questions asked by interviewers at large companies (Source: Interview Prep Articles) to help users be better prepared. Although these questions are not generic/common, it helps if the interviewee has an intuition of how they can answer these questions, because similar questions are definitely going to be asked.
=> contents: add behavioral questions

contents/interview-formats.md
Added Amazon interview roadmap
=> contents: add Amazon interview format

contents/study-and-practice.md
Replaced the link to lago with TheAlgorithms and switched up the sentence a bit
=> contents: replace Lago with TheAlgorithms

contents/algorithms/binary.md
This representation may be easier to understand for some people.
If a number is power of two then `AND` operation between the number and 2's complement of the number will result into the same number.
=> content: check if a number is a power of 2

contents/algorithms/sorting-searching.md
Closes https://github.com/yangshun/tech-interview-handbook/issues/190
=> algo: remove similar question

contents/resume.md
It would be ideal to have the list of "10 ways to improve your resume" in a numbered format.
This makes it easier to read & follow through especially when someone is doing note-taking.
=> Numbering the 10 ways

contents/coding-signals.md
- add punctuation
- correct pronoun agreement
=> contents: update coding signals

website/blog/2021-08-30-my-experience-with-front-end-interviews.md
=> blog: add front end interview experience blog post

contents/algorithms/binary.md
This swaps the two values in the two variables without needing a third variable.
=> contents: include a snippet for swapping two variables using bitwise operators

contents/algorithms/oop.md
Design a parking lot system is an important sample question in low-level design. It would be great if this question is added.
=> contents: add Parking Lot question to OOP

contents/interview-formats.md
dropbox.com with full stop begin dropbox.com(.) it leads to 404 page from dropbox
=> fix: dropbox.com is connected with full stop

contents/algorithms/dynamic-programming.md
"Partition Equal Subset Sum" and "0/1 Knapsack".
Don't think this is very useful, but given that there was an issue 🤷.
Closes #234
=> contents: make the Partition Equal Subset Sum link both

README.md
<b>There had been multiple grammatical errors in this document which has been corrected now.</b>
=> misc: corrected some grammatical errors in README file

README.md
=> Added Simplify!

contents/algorithms/dynamic-programming.md
Added BaseCS blog post on Dynamic Programming to study links section
=> contents: add more resources for DP

contents/introduction.md
Noticed the phrase _'It was a tedious process which I don't ever want to go through again'_ was being repeated in the introduction page:
=> contents: remove repeated sentence in introduction

contents/programming-languages-for-coding-interviews.md
Most languages let >>> Most companies let
=> contents: fix typo in programming languages page

contents/algorithms/matrix.md
Found a typo in the comments of Python code snippet
=> contents(algo): fix typo in matrix cheat sheet

contents/algorithms/array.md, contents/algorithms/binary.md, contents/algorithms/graph.md, contents/algorithms/heap.md, contents/algorithms/stack.md, contents/algorithms/study-cheatsheet.md, contents/algorithms/tree.md
Suggestions:
- Heap page: Potentially mention that for python heapq you can push the inverse value to find the max
- Tree page: Traversing balanced tree is O(h) space
Please correct me if I am wrong!
=> contents: algorithm cheatsheet typos and suggestions

website/src/pages/index.js
=> Omitted double "and" on home page

contents/algorithms/study-cheatsheet.md
hash tables are >>> Hash table is
=> contents: fix typo and grammar in study cheatsheet

website/src/data/successStories.js
Success story from Rahul Senguttuvan ( Current Intern at Meta )
=> website: add Rahul Senguttuvan's success story

website/src/data/successStories.js
=> website: add Jeanne Toh's success story

apps/website/contents/choosing-between-companies.md
Small typo I found while going over the content, great stuff thanks for putting it together!
=> contents: fix typo in choosing between companies

.vscode/settings.json, apps/portal/prisma/migrations/20221005155047_add_resume_schemas/migration.sql, apps/portal/prisma/migrations/20221006064944_add_resume_schemas/migration.sql, apps/portal/prisma/schema.prisma
https://lucid.app/lucidchart/bcaf2307-e8df-4eba-b505-9c869e95cffc/edit?invitationId=inv_244e5678-2aad-4510-8701-22c94b320e7d&page=0_0#
=> [resumes][feat] add resumes schema

packages/ui/src/Collapsible/Collapsible.tsx
Adds an optional `defaultOpen` prop.
=> [ui][collapsible] add defaultOpen prop

apps/portal/src/components/resumes/browse/BrowsePageBody.tsx
- Add search bar
- Add 'new' button
- Refactor code
=> [resumes][feat] Add missing browse page UI

apps/portal/src/components/resumes/comments/CommentsForm.tsx, apps/portal/src/components/resumes/comments/CommentsList.tsx, apps/portal/src/components/resumes/comments/comment/Comment.tsx, apps/portal/src/components/resumes/comments/comment/CommentBody.tsx, apps/portal/src/components/resumes/comments/comment/CommentCard.tsx, apps/portal/src/pages/resumes/[resumeId].tsx, apps/portal/src/server/router/resumes-reviews-router.ts, apps/portal/src/types/resume-comments.d.ts
What's new
- Fetch and render comments from database. Owner comments are right-aligned and others are left-aligned
What's next:
- Upvote comments
- Edit comments
=> [resumes][feat] fetch comments from database 

apps/portal/src/pages/resumes/index.tsx, apps/portal/src/pages/resumes/submit.tsx
https://user-images.githubusercontent.com/53945359/194709692-2ab7606b-342d-437e-88f7-ba91c962fb78.mov
=> [resumes][feat] Add basic linking of pages

apps/portal/src/components/resumes/browse/constants.ts, apps/portal/src/components/resumes/comments/CommentsForm.tsx, apps/portal/src/pages/resumes/index.tsx, apps/portal/src/pages/resumes/submit.tsx
Align to use the same experience, roles, location list
=> [resumes][feat] add required fields and use text area

apps/portal/src/components/resumes/ResumePdf.tsx, apps/portal/src/components/resumes/browse/constants.ts, apps/portal/src/components/resumes/comments/CommentsSection.tsx, apps/portal/src/pages/resumes/[resumeId].tsx, apps/portal/src/pages/resumes/index.tsx, apps/portal/src/pages/resumes/submit.tsx
- Responsive UI for review page
- Center pdf view in middle of page
- Center spinners
- Uppercase location values (temporary fix for lowercase location values displayed, will switch to enums once they are ready)
https://user-images.githubusercontent.com/35712975/194740905-67130786-10d1-4d27-a9ea-237dce80fa44.mov
=> [resumes][fix] add spinners and responsive UI

apps/portal/src/pages/resumes/submit.tsx, packages/ui/src/CheckboxInput/CheckboxInput.tsx
Add submission guidelines box to submit form.
=> [resumes][feat] add submission guidelines box

apps/portal/src/components/resumes/ResumesNavigation.ts, apps/portal/src/components/shared/MonthYearPicker.tsx, apps/portal/src/pages/index.tsx
@yangshun Fixed the CI issue as well, need to convert number to Month 😄
=> [resumes][feat] Update resume top nav bar

.github/workflows/tsc.yml, apps/storybook/package.json, package.json
So that the `yarn tsc` command check is run on every PR.
=> [infra] add GitHub action for typechecking

apps/portal/src/components/global/ProductNavigation.tsx
Add redirection for navigation items with `target: "_blank"`
=> [app/portal][fix] Add tab redirection 

apps/portal/src/components/resumes/browse/ResumeListItem.tsx, apps/portal/src/components/resumes/browse/resumeConstants.ts, apps/portal/src/pages/resumes/[resumeId].tsx, apps/portal/src/pages/resumes/index.tsx, apps/portal/src/pages/resumes/submit.tsx
- star resumes button shows a spinner when waiting for server response
- refactor components to use `@tih/ui` Menu and Checkboxes
- add filtering logic
- add search filtering logic
- add sorting logic
=> [resumes][feat] resumes sorting and filtering

apps/portal/src/pages/resumes/[resumeId].tsx, apps/portal/src/pages/resumes/submit.tsx, apps/portal/src/server/router/resumes/resumes-resume-user-router.ts
* Resumes review
* Track edit / view state
* Reused submit form, but changed:
* Clear --> Cancel functionality
* Fetch PDF when form loads
=> [resumes][feat] add edit form functionality

apps/portal/src/components/resumes/comments/ResumeCommentListItem.tsx, apps/portal/src/server/router/resumes/resumes-comments-user-router.ts
- Add edit functionality to resume comments
https://user-images.githubusercontent.com/45381509/196372380-e5360953-71b4-4abf-8ade-3afd184d26b0.mp4
=> [resumes][feat] add comment edit

apps/portal/src/components/resumes/comments/ResumeCommentListItem.tsx, apps/portal/src/server/router/index.ts, apps/portal/src/server/router/resumes/resumes-comments-router.ts, apps/portal/src/server/router/resumes/resumes-comments-upvotes-user-router.ts, apps/portal/src/server/router/resumes/resumes-comments-votes-router.ts, apps/portal/src/server/router/resumes/resumes-comments-votes-user-router.ts, apps/portal/src/types/resume-comments.d.ts
Add upvote/downvote feature to resume comments
- Abstracted the fetching of upvotes/downvotes to individual comment components
https://user-images.githubusercontent.com/45381509/196600421-03e9de88-a52e-4a27-a101-65e56def483f.mov
=> [resumes][feat] Add resume comment upvote/downvote

apps/portal/src/components/resumes/comments/ResumeCommentListItem.tsx
To give the user a visual prompt when voting
=> [resumes][feat] Add spinner when rating comments

apps/portal/src/components/resumes/comments/ResumeCommentListItem.tsx
- Add animation to voting while query is still being processed
- Remove spinner
Team decided that this is a better visual prompt
https://user-images.githubusercontent.com/45381509/196688990-e89ae337-7ef2-4d28-b04b-aa0a2ee71ae0.mp4
=> [resumes][feat] Update vote animation

apps/portal/src/components/resumes/comments/ResumeCommentListItem.tsx, apps/portal/src/components/resumes/comments/comment/ResumeCommentVoteButtons.tsx, apps/portal/src/server/router/resumes/resumes-comments-router.ts
Touchup the comment UI
- Added a vertical line for replies
- Added `min-width` to comment vote count so the width does not keep changing
- Sort comments in ascending order (not in video)
https://user-images.githubusercontent.com/45381509/197152315-b9e70d98-45df-41a3-a742-acff92484331.mp4
=> [resumes][refactor] Comment UI touchup

apps/portal/src/components/offers/constants.ts, apps/portal/src/components/offers/offersSubmission/OffersSubmissionForm.tsx, apps/portal/src/components/offers/offersSubmission/submissionForm/BackgroundForm.tsx, apps/portal/src/components/offers/offersSubmission/submissionForm/OfferDetailsForm.tsx, apps/portal/src/components/offers/table/OffersRow.tsx, apps/portal/src/pages/offers/home.tsx, apps/portal/src/pages/offers/profile/[offerProfileId].tsx
=> [offers][fix] Use title typeahead

apps/portal/prisma/migrations/20221014105030_add_question_content_search/migration.sql, apps/portal/prisma/schema.prisma, apps/portal/src/server/router/questions-question-router.ts
Reverts yangshun/tech-interview-handbook#412
=> Revert "[questions][feat] add text search"

apps/portal/src/server/router/resumes/resumes-comments-votes-router.ts
Vote query was not retrieving whether a user has upvoted/downvoted a comment
=> [resumes][fix] update vote query

apps/portal/src/components/resumes/comments/ResumeCommentsList.tsx, apps/portal/src/pages/resumes/[resumeId].tsx, apps/portal/src/pages/resumes/browse.tsx
* Use primary buttons for "Submit resume" and "Add your review"
* Add edit text to button for consistency
=> [resumes][feat] use primary buttons

apps/portal/src/components/resumes/ResumePdf.tsx, apps/portal/src/components/resumes/browse/ResumeListItem.tsx, apps/portal/src/components/resumes/landing/PrimaryFeatures.tsx, apps/portal/src/pages/resumes/[resumeId].tsx, apps/portal/src/pages/resumes/browse.tsx, apps/portal/src/pages/resumes/index.tsx, apps/portal/src/utils/resumes/resumeFilters.ts, packages/ui/src/Pagination/Pagination.tsx
**Marketing Page**
- Update Tabs CSS to occupy full pill when clicked
=> [resumes][refactor] Update app UI

apps/portal/src/pages/resumes/browse.tsx, apps/portal/src/pages/resumes/submit.tsx, apps/portal/src/server/router/resumes/resumes-resume-router.ts, apps/portal/src/utils/resumes/resumeFilters.ts
=> [resumes][feat] Add filter counts on browse page

apps/portal/src/pages/resumes/index.tsx, apps/portal/src/server/router/resumes/resumes-resume-router.ts, apps/portal/src/server/router/resumes/resumes-resume-user-router.ts, apps/portal/src/utils/resumes/resumeFilters.ts
https://user-images.githubusercontent.com/53945359/198822543-292529ee-a9d6-404f-8d20-825b0534e016.mov
=> [resumes][feat] Add dynamic filters and unreviewed shortcut

apps/portal/src/components/resumes/comments/ResumeCommentsForm.tsx, apps/portal/src/components/resumes/comments/comment/ResumeCommentReplyForm.tsx, apps/portal/src/components/resumes/comments/comment/ResumeCommentVoteButtons.tsx
GA events for
- Submitting comments
- Replying comments
- Voting and un-voting
=> [resumes][feat] add ga for comments

apps/portal/package.json, apps/portal/prisma/seed-questions.ts
Adds a question seeding script that can be run using `yarn seed-questions`.
=> [questions][chore] add questions seeding script

apps/portal/src/components/questions/AddToListDropdown.tsx, apps/portal/src/components/questions/ContributeQuestionCard.tsx, apps/portal/src/components/questions/VotingButtons.tsx, apps/portal/src/components/questions/card/question/BaseQuestionCard.tsx, apps/portal/src/components/questions/protected/ProtectedContextProvider.tsx, apps/portal/src/components/questions/protected/ProtectedDialog.tsx, apps/portal/src/pages/_app.tsx, apps/portal/src/pages/questions/[questionId]/[questionSlug]/answer/[answerId]/[answerSlug]/index.tsx, apps/portal/src/pages/questions/[questionId]/[questionSlug]/index.tsx, apps/portal/src/pages/questions/lists.tsx, apps/portal/src/utils/questions/useProtectedCallback.ts
useProtectedCallback wraps action callbacks that require authorization. If the user is not authorized, a dialog will be shown prompting the user to sign in.
=> [questions][feat] add useProtectedCallback hook

apps/portal/src/components/offers/JobTypeTabs.tsx, apps/portal/src/components/offers/offersSubmission/submissionForm/OfferDetailsForm.tsx, apps/portal/src/pages/offers/index.tsx, packages/ui/src/Tabs/Tabs.tsx
=> [offers][fix] tweak submit offer job type selector

apps/portal/src/components/offers/offersSubmission/OffersSubmissionForm.tsx, apps/portal/src/components/offers/offersSubmission/submissionForm/OfferDetailsForm.tsx, packages/ui/src/HorizontalDivider/HorizontalDivider.tsx
Changes made:
- Tweaked spacing between form elements and between offer cards and padding within
- Added section headings to give some sense of hierarchy to the form
- Make form elements take up full width on mobile
- Change color of buttons slightly
=> [offers][feat] tweak offer details submission form

apps/portal/src/components/offers/Breadcrumb.tsx, apps/portal/src/components/offers/forms/FormSection.tsx, apps/portal/src/components/offers/offersSubmission/OffersSubmissionForm.tsx, apps/portal/src/components/offers/offersSubmission/submissionForm/BackgroundForm.tsx, apps/portal/src/components/offers/offersSubmission/submissionForm/OfferDetailsForm.tsx
=> [offers][feat] tweak offer background submission form

packages/ui/src/Button/Button.tsx
- Added `rel` and `target` properties to Button for opening new tabs
=> [ui][button] Add rel and target properties to button

apps/portal/prisma/migrations/20221108061935_add_comment_deletion/migration.sql, apps/portal/prisma/schema.prisma, apps/portal/src/components/resumes/comments/ResumeCommentListItem.tsx, apps/portal/src/components/resumes/comments/comment/ResumeCommentDeleteForm.tsx, apps/portal/src/server/router/resumes/resumes-comments-user-router.ts
Add deletion of comments
- Deletion cascades; All the replies will also be removed
=> [resumes][feat] delete comment

apps/portal/src/pages/resumes/[resumeId].tsx, apps/portal/src/server/router/resumes/resumes-resume-user-router.ts
Add deletion of resumes
- Deletion cascades; All comments, votes and stars will also be removed
- User is redirected to the `browse` page after deletion
=> [resumes][feat] add deletion for resumes

apps/website/contents/algorithms/stack.md
Fixes: https://github.com/yangshun/tech-interview-handbook/issues/552
=> [website][fix]: change LC link for Implement Stack using Queues

apps/website/contents/resume.md
Completed a Sentence at resume.md at Line no 336
=> [website][fix] fix incomplete line in resume guide

apps/website/contents/algorithms/hash-table.md, apps/website/contents/algorithms/tree.md
Adds links to online lectures and slides from
data structures and algorithms course covering
hash tables, binary search trees, red-black trees
and b-trees.
=> contents: add links to extra resources (video lectures)

apps/website/contents/algorithms/sorting-searching.md
This commit supplements the reading material for sorting algorithms with an additional set of public video lectures and corresponding slides.
=> contents(sorting): add video resources to sorting and searching

apps/website/contents/self-introduction.md
=> contents: improve self introduction explanation

apps/website/contents/algorithms/geometry.md
I found a minor typo while going over the content in the algorithm/geometry section.
Thanks for the handbook!
=> contents(algo): fix typo in algorithm/geometry content

apps/website/contents/behavioral-interview.md
Added more content to the behavioral interview section.
I wasn't able to test my changes since I cannot run the project locally (misisng env variables). I checked the formatting in an online markdown viewer and it looked fine - https://codebeautify.org/markdown-viewer/y23a7b915
=> contents(behavioral): add more information for Behavioral Interviews

apps/website/contents/algorithms/graph.md
changed typo error from "disjoint graphs" to "Disconnected graphs"
Fixes #545
=> contents(algo): s/disjoint/disconnected

apps/website/contents/software-engineering-interview-guide.md
Great content! Happened to find this grammar issue and sending a fix
=> contents: remove some stuttering when showcasing mock interview solutions

apps/website/contents/coding-interview-rubrics.md
=> contents: fix typo in coding-interview-rubrics.md

apps/website/contents/coding-interview-rubrics.md
=> contents: misc update to coding-interview-rubrics.md

apps/website/contents/software-engineering-interview-guide.md
Breaking this out into bullet points for easier reading of the acronym
=> contents(star): Bullet point formatting

apps/website/contents/system-design.md
Added https://roadmap.sh/system-design into the free resources list
Fixes #592
=> contents(sd): add roadmap.sh to free resource list

apps/website/contents/algorithms/graph.md
I found a minor typo while going over the content in the algorithm/graph section. 
Thanks for the handbook! It is a gem!
=> contents(algo): fix typo in algorithm/graph content

apps/website/contents/algorithms/sorting-searching.md
I fixed the broken URL for Khan Academy's Binary Search.
=> contents: khan academy link for binary search fixed

apps/website/contents/resume.md
The branch `feature/add-section-CV-cover-letter` adds 900 words to the `resume.md`. The changes provide valuable advice on a topic that has not been mentioned in the TIH and it's very relevant in the hiring process. 
This is the structure of the new sections added:
1. Crafting the Perfect Cover Letter
2. Common Pitfalls to Avoid on your Cover Letter
3. Practical Tips
4. Cover Letter Example and Evaluation
Tested the changes locally using `yarn dev:website`. Everything looks fine. Screenshot attached of the `live` version and my `localhost:3000` 👇 
As we're reviewing content and not code, I'm providing a link to a Google Docs. Feel free to make any comments/suggestions/edits in the document and I'll propagate the changes to the `resume.md` and re-raise the PR.
[[Link to Google …
=> contents: add Cover Letter section to resume page

README.md
Changing Name of Twitter to X (Twitter)
This fixes  https://github.com/yangshun/tech-interview-handbook/issues/615
=> misc: change "Twitter" to "X (Twitter)"

apps/website/contents/career-growth.md
Thanks for creating this awesome list!
Adding in my newsletter and LinkedIn content profile, thanks!
=> contents(beyond): add Hungry Minds and myself to LinkedIn resources

apps/portal/src/pages/resumes/[resumeId].tsx
When screen width is between lg to xl, the button is hidden
=> [resumes][fix] fix missing [add review]/[sign in to comment] buttons

apps/website/contents/resume.md
=> contents: fix typo in resume.md

apps/website/blog/2019-11-03-are-front-end-development-enough-for-a-career.md, apps/website/blog/2021-04-12-importance-of-communicating-effectively-as-an-engineer.md, apps/website/blog/2021-08-19-facebook-career-questions-and-answers.md, apps/website/blog/2021-08-28-front-end-career-questions.md, apps/website/blog/2021-08-30-a-glimpse-into-front-end-interviews.md
Rectify Ahrefs issue for Canonical points to redirect by using final links after redirect chains for canonical links
=> seo: fix canonical points to redirect issue

apps/website/blog/2021-12-23-front-end-vs-back-end-system-design-interviews.md, apps/website/blog/2022-04-20-take-control-over-your-coding-interview copy.md
Some of Zhenghao's blog posts that were canonical links seem to be removed, removed the corresponding canonical links
=> seo: fix canonical points to 4xx issue

apps/portal/src/pages/resumes/about.tsx
Added a title tag for https://app.techinterviewhandbook.org/resumes/about
=> app/resumes: fix title tag missing
