- non-technical/behavioral.md
The `behavioral.md` file uses `–` instead of `-` on two lines, resulting in slightly broken formatting.
> Fix formatting in the behavioral.md file

- algorithms/string.md
Fix the issue: https://github.com/yangshun/tech-interview-handbook/issues/19
The given example was not correct:
'E.g. "abba" and "redblueredblue" should return true'
It has ben fixed by changing the input "redblueredblue" to "redbluebluered"
> Fix typo issue

- front-end/javascript.md
Hi yangshun,
I think it's good to mention the `async` and `await` keywords in ES7 in the Async section.
What's your opinion?
> Add async and await in the Async section

- front-end/interview-questions.md
Hi @yangshun, 
A small highlight syntax fix for `front-end/interview-questions.md`
P/S: Great handbook btw 👏. Do you have any plan adding React interview questions?
> Fix js syntax highlight in interview-questions

- front-end/interview-questions.md
Awesome guide. Just removed a small typo with 'the' and 'a' in the JSONP answer.
> Removed 'the' in jsonp answer.

- non-technical/questions-to-ask.md
The original phrasing was a little awkward, had grammar issues, referred to the interviewer (you) directly, and assumed the hired person to be a male. This change addresses those issues.
> questions-to-ask.md: improve phrasing & grammar

- utilities/javascript/deepEqual.js
If deepEqual is invoked with an empty object and null, it throws TypeError.
> deepEqual throws exception

- contents/understanding-compensation.md
Disclosure: I'm one of the makers of Levels.fyi.
This is obviously a big red flag that I'm adding a reference to a site I have an interest in. I think the community would find our data useful and more accurate than alternatives. A quick search on Google would bring up that folks regularly consult data on our site over say Glassdoor, etc.
> Add references to compensation data

- README.md
Fix broken url for `Interview formats` on README.md
> misc: fix broken link for /interview-formats

- contents/algorithms/graph.md
Algorithm performed a dfs rather than bfs because of the queue.pop() error on line 78. Updated to queue.popleft()
> Fixing small issue with bfs algorithm

- contents/cheatsheet.md
Fixes #143 
`behaioral` -> `behavioral`
> misc: fixed typo in cheatsheet

- design/README.md
The link from task11 in https://medium.com/free-code-camp/the-ultimate-guide-to-preparing-for-the-coding-interview-183251ee36c9 is broken. Fixing it by providing a reference to the right url
> misc: create backwards-compatibility README for system design

- contents/understanding-compensation.md
There're different numbers mentioned in Alice salary description and bonus calculation.
> Alice is an Engineering Manager with 10 years of professional experience. Her base salary is **_220,000_**, is an experienced engineering manager (seniority multiplier: 20%), exceeded expectations for the half (individual performance multiplier: **_150_**%) and her company did pretty awesome (company performance multiplier: 130%). For that half, her bonus will be as follows:
>Bonus: **_200,000_** x 50% (half a year) x 20% (seniority) x **_200_**% (individual performance) x 130% (company performance) = **_39000_**
The bonus paragraph should become:
>Bonus: **_220,000_** x 50% (half a year) x 20% (seniority) x **_150_**% (individual performance) x 130% (company performance) = **_42900_**
> contents: Fix typo in Alice compensation example

- contents/algorithms/array.md
while solving the [Product of Array Except Self](https://leetcode.com/problems/product-of-array-except-self/) I saw that traversing the array twice helped me solve the problem easily in O(n) time complexity. adding the line will make the interviewee free from the mental barrier that they can traverse the array more than once even if the time complexity asked is O(n).
> contents: add tip on traversing arrays

- contents/algorithms/linked-list.md
This was a source of confusion for me because you technically need to search for the linked list node first, which takes O(n) time in the average and worst case scenarios. I think it'll be easier to understand if we clarify that the node is already found as done in this [StackOverflow answer](https://stackoverflow.com/a/14048223). If you think that this distinction is not necessary and confuses things more, then feel free to close the PR.
> contents: update linked list insertion and deletion explanation

- contents/algorithms/hash-table.md
std::map is compare-based, the hash table in the standard library is std::unordered_map
https://en.cppreference.com/w/cpp/container/map
https://en.cppreference.com/w/cpp/container/unordered_map
> contents: std::map is not a hash-table

- contents/algorithms/math.md
Found a typo in the math cheat sheet for using epsilon comparisons for floats. I believe this should be 10e-7 rather than 10e7, as we would be interested in precision after the decimal.
Please let me know if I am wrong as I am not very familiar with this. 😄
> contents(algo): fix typo in math cheat sheet

- contents/_components/QuestionGroups.json
At least as of today 2022/07/02, the `Min Stack` problem is of `Medium` difficulty instead of `Easy` https://leetcode.com/problems/min-stack/
> contents: fix min stack difficulty

- apps/portal/prisma/schema.prisma
- apps/portal/src/components/resumes/comments/CommentsForm.tsx
- apps/portal/src/components/resumes/comments/CommentsList.tsx
- apps/portal/src/components/resumes/comments/CommentsListButton.tsx
- apps/portal/src/components/resumes/comments/CommentsSection.tsx
- apps/portal/src/components/resumes/comments/constants.ts
- apps/portal/src/pages/resumes/review.tsx
- apps/portal/src/server/router/index.ts
- apps/portal/src/server/router/resumes-reviews-router.ts
- apps/portal/src/server/router/resumes-reviews-user-router.ts
What's new:
- Set up the backend route to create resume reviews.
- Set up route to query for reviews of a given `resumeId`
How to test:
- Currently incomplete as `review.tsx` does not contain `resumeId` required for mutation and query. Need to pass `resumeId` from `Browse` > `Review` > `CommentSection` component for this to work properly
- For local testing: Add a dummy resume with the `Submit` form and hard-code `resumeId` in `CommentSection`
Fields queried for comment:
- Comment information
- User name, image
- Number of votes 
- Whether the user (if-any) has voted this comment
> [resumes][feat] Add API to submit & query for resume reviews

- apps/portal/src/components/questions/filter/FilterSection.tsx
- apps/storybook/stories/checkbox-list.stories.tsx
- Radio spacing too large: This spacing is actually fine, the checkboxes weren't using the `CheckboxList` component, which would use the same amount of spacing as the `RadioList`.
- Typeahead overlapping issue: There was a `z-10` added to a `<div>` wrapping the typeahead. I think because I fixed the issue within the `Typeahead` component, there's no longer a need for that z-index. Lemme know if I'm missing something here.
cc @jeffsieu
> [questions][fix] tweak question filters

- apps/website/contents/behavioral-interview.md
Fixes Issue #569 
Fixed a typo in the [**Try out mock behavioral interviews** section](https://github.com/yangshun/tech-interview-handbook/blob/main/apps/website/contents/behavioral-interview.md#4-try-out-mock-behavioral-interviews):
`Apply` -> `Apple`.
> misc: fixed typo in behavioral interview

- apps/website/contents/algorithms/hash-table.md
java.util.TreeMap is actually an implementation of the Red-Black tree, rather than a hashtable. This is a minor change to remove that from the list of implementations for hastable in Java.
> contents(algo): remove java.util.TreeMap from Hashtable implementations

- apps/website/contents/algorithms/sorting-searching.md
Added details about which specific sorting algorithms are provided by the Java language/platform.
> contents(algo): add Java implementation details for platform sorting algorithms

- apps/website/contents/mock-interviews.md
Adding https://www.hellointerview.com to mock interviews. Added similar disclaimer to meetapro (though I'd love to hear any  take you might have!)
Thanks so much for building TIH, what an invaluable resource for the SWE community.
Oblig. testing image:
> [Content] Add Hello Interview to mock interviews

- apps/website/contents/behavioral-interview-questions.md
Two first behavioural questions for Palantir were styled as **bold**.  After the change they have the same styling as any other behavioural questions in this document.
> contents: style of Palantir questions is aligned with style of other questions

- apps/website/contents/algorithms/queue.md
Fixed a typo in the "Things to look out for during interviews" section. It previously stated that enqueue had a time complexity issue in languages without built-in Queue classes using arrays. It's actually the dequeue operation that's O(n) due to front removal and shifting of elements. Fixing this small typo for clarity.
> contents(queue): fix typo in queue content

- .gitignore
- apps/website/contents/career-growth.md
- apps/website/sidebars.js
Spoke with @yangshun: We can add a "Career Growth" page under Misc which points to some of the top resources for engineers to grow in their careers.
I curated the resources that will be most relevant and I can personally attest to from the [Path to Senior Engineer Handbook](https://github.com/jordan-cutler/path-to-senior-engineer-handbook)
> contents: Add Misc > Career Growth Page

- apps/website/contents/career-growth.md
Add 16x Engineer created by myself: https://16x.engineer/
It is a website dedicated to resources on Software Engineer Career and Personal Growth, with a focus on Asia and Singapore tech industry.
Since there is no dedicated website category, I have parked in under newsletter (the website does have its own newsletter).
> contents(beyond): add 16x Engineer

- apps/website/contents/career-growth.md
I recently updated https://careercutler.substack.com/ to be https://read.highgrowthengineer.com/
This PR updates to the new domain.
Note: The original redirects to the new one, but it will be better to use the new one.
> contents(career): update High Growth Engineer URL to new domain

- apps/website/contents/coding-interview-prep.md
This PR fixes a typo in the coding interview description, where "access" was mistakenly used instead of "assess."
The correction improves clarity in the sentence about assessing competencies during interviews.
Closes:
> [fix] Correct typo from 'access' to 'assess' in interview description (#663)

- apps/website/contents/_courses/AlgorithmCourses.md
fixes #649
updated the broken link  "https://fxo.co/DQpY" to "https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms/?couponCode=ST18MT62524"
> update Udemy course link

- apps/website/contents/self-introduction.md
Updated text on self introduction page to match references to it further down in the breakdown section.
> [content] fix typo on Self Introduction page

- apps/website/src/pages/index.js
This PR should close #665, I have changed the hyperlink for the text `Open a pull request!` specificially in [this file](https://github.com/yangshun/tech-interview-handbook/blob/main/apps/website/src/pages/index.js) from this [invalid link](https://github.com/yangshun/tech-interview-handbook/edit/master/website/src/data/successStories.js) to the [working link](https://github.com/yangshun/tech-interview-handbook/edit/main/apps/website/src/data/successStories.js). As previously mentioned, it is advised that you edit the issue #255, adding the working link instead.
> [fix] update hyperlink for "Open a pull request!" on home page

- apps/website/contents/algorithms/linked-list.md
Add `std::list` as the linked list implementation in C++.
> contents: add linked list implementation in C++

- apps/website/contents/algorithms/array.md
In arrays section, there's a leetcode reference for **_Master the sliding window technique_**. Currently, the [existing link](https://discuss.leetcode.com/topic/30941/here-is-a-10-line-template-that-can-solve-most-substring-problems) redirects to https://leetcode.com/discuss/post/topic/30941/ which is broken. This patch updates the link to the originally referred post in Leetcode.
**Before patch:**
**After patch:**
> fix: update the broken hyperlink for "Master the sliding window technique" on arrays

- apps/website/blog/2022-07-09-getting-a-tech-job-as-an-undergraduate.md
- apps/website/contents/best-practice-questions.md
- apps/website/contents/coding-interview-prep.md
- apps/website/contents/software-engineering-interview-guide.md
- apps/website/docusaurus.config.js
- apps/website/src/data/successStories.js
Ensure all grind 75 links are `https://www.techinterviewhandbook.org/grind75/` mostly by adding trailing slashes, added www for one link
> seo: fix 3xx redirects issue

- apps/portal/src/pages/_document.tsx
app.techinterviewhandbook.org slugs were missing HTML lang attribute
> seo: fix HTML lang attribute missing
